print( " ------------------------------------------------")
print("|                                                |")
print("|    01HelloWorld                                |")
print("|    Name : Ellie Liu                            |")
print("|    Version : 01                                |")
print("|                                                |")
print( " -----------------------------------------------")
print("Hello World")
