print( " ------------------------------------------------")
print("|                                                |")
print("|    02GoodbyeWorld                              |")
print("|    Name : Ellie Liu                            |")
print("|    Version : 01                                |")
print("|                                                |")
print( " ------------------------------------------------")
print("Hello World")
input("------> Program paused - press enter to continue")
print("Goodbye World")